### ISSUE TITLE
issue-3-search-for-a-pokemon

### ISSUE THREAD

**Issue by hollyphung95** [hollyphung95/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for a specific pokemon.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user types into a search bar and submits their search keywords, a list of pokemon is loaded from the pokemon API and displayed on the page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

**HTML**
   - [ ] Add a `div[data-search=“search-form"]` to the HTML.
   - [ ] Add a form for creating a search bar to the `div[data-search=“search-form"]`.
**CSS**
   - [ ] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
   - [ ] Make all inputs of the search form `required`.
**JS**
-    - [ ] Listen for `'input'` events on the `search` input to update the `data-search` attribute of the collection preview when the input value changes.
- [ ] ...
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
