### ISSUE TITLE
issue-1-create-a-collection

### ISSUE THREAD

**Issue by hollyphung95** [hollyphung95/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a pokemon to a collection .

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a responsive form that allows users to store a new collection of cards of their favorite pokemon.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

**HTML**
- [ ] Add a `div[data-view=“collection-form"]` to the HTML.
- [ ] Add a form for creating a collection to the `div[data-view=“collection-form"]`.
**CSS**
- [ ] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [ ] Make all inputs of the collection form `required`.
**JS**
- [ ] Listen for `'input'` events on the `text` input to update the `data-collection` attribute of the collection preview when the input value changes. if their input matches any collection's name that is currently in their list of collections. notify the user the name is unavailable.
- [ ] Listen for `'submit'` events on the collection form and:
  - [ ] Put the form's input values into a new object.
    - [ ] Put the form's text input value into a new object.
    - [ ] Put the form's radio input values into a new object.
    - [ ] Put the form's submit input value into a new object.
  - [ ] Add the `data-nextCardId` to the object.
  - [ ] Increment the `nextCardId` on the data model.
  - [ ] Prepend the new object to the collection in the data model.
  - [ ] Reset the data-cards attribute.
  - [ ] Reset the form inputs.
- [ ] Verify that new cards are saved to local storage along with the rest of the data model on page reload.
- [ ] Verify that each new collection receives an incrementing `collectionId`.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
