### ISSUE TITLE
issue-2-view-a-collection

### ISSUE THREAD

**Issue by hollyphung95** [hollyphung95/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their collections.

## 📐 Functionality

> ##### Once a user has added some pokemon to their collections, they'll want to see them.

Display the user's pokemon collections in reverse chronological order so they can see the newest ones first.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add a sibling `div[data-view="collections”]` to the HTML.
- [ ] Add an empty unordered list to the `div[data-view="collections”]` element in the HTML.
- [ ] Add some dummy pokemon collections to the unordered list in the HTML and style them to match the wireframe.
- [ ] Check that the collections list looks good on both mobile and desktop screens.
- [ ] Define a function that takes a single pokemon `collection` object and returns a DOM tree that matches one of the example cards in the HTML.
- [ ] Use a loop to create a DOM tree for each journal collection in the data model and append it to the page when the `'DOMContentLoaded'` event is fired.
- [ ] Remove the example HTML cards once the user's cards are successfully being appended to the DOM on page load.
- [ ] Add a navigation item to the navbar for collections.
- [ ] Add an anchor to the collections view that shows the collection form.
- [ ] Ensure that submitting a new pokemon collection also creates a new DOM tree for it and adds it to the page.
- [ ] Ensure that submitting a new pokemon collection automatically shows the `'collections'` view without reloading the page.
- [ ] Ensure that refreshing the pages shows the same view as before refreshing.
- **Clean Up**
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
