### ISSUE TITLE
issue-4-edit-a-collection

### ISSUE THREAD

**Issue by hollyphung95** [hollyphung95/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit a collection.

## 📐 Functionality

> ##### If a user doesnt want certain pokemon saved in a collection anymore, they should be able to edit their collection.

Allow users to select existing cards to edit and pre-populate its information into the form.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Update card rendering function to include an edit icon for each rendered card.
- [ ] Ensure that each rendered card is given a `data-card-id` attribute indicating which card it is.
- [ ] Listen for clicks on the parent element of all rendered cards.
- [ ] Show the card form if an edit icon was clicked.
- [ ] Find the matching card object in the data model and assign it to the data model's `editing` property if an edit icon was clicked.
- [ ] Pre-populate the card form with the clicked card's values from the object found in the data model.
- [ ] Update the card form's submit handler function to conditionally add a new card object or update the existing one.
- [ ] Update the card form's submit handler function to conditionally add a new card DOM tree or replace the existing one.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
