### ISSUE TITLE
issue-5-delete-a-card-or-collection

### ISSUE THREAD

**Issue by hollyphung95** [hollyphung95/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a card/collection.

## 📐 Functionality

> ##### If a user decides that they no longer wish to keep a card in a collection or want to completely discard a collection, they should be able to delete it.

Allow users to delete a card/collection from its edit screen.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add a click target for deleting a collection to the collection form that only appears if the user is editing a collection.
- [ ] Show a confirmation modal when the user clicks the Delete collection click target.
- [ ] Hide the modal if the user clicks Cancel.
- [ ] Remove the collection from the data model ad the collection's DOM tree from the page if the user clicks Delete.
- [ ] Show the collection list if the user clicks Delete.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
